"""initial schema

Revision ID: cc3b2d8e77cc
Revises: 
Create Date: 2026-06-02 13:32:48.920737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc3b2d8e77cc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('wedding', 'bar_mitzvah', 'brit', 'birthday', 'other', name='event_type'), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('is_mine', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('relation', sa.Enum('family', 'friend', 'work', 'other', name='relation'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('direction', sa.Enum('given', 'received', name='direction'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_event_id'), 'transactions', ['event_id'], unique=False)
    op.create_index(op.f('ix_transactions_person_id'), 'transactions', ['person_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_person_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_event_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('persons')
    op.drop_table('events')
    # Postgres keeps native ENUM types after their tables are dropped; remove
    # them explicitly so a later re-upgrade doesn't hit "type already exists".
    sa.Enum(name='direction').drop(op.get_bind())
    sa.Enum(name='event_type').drop(op.get_bind())
    sa.Enum(name='relation').drop(op.get_bind())
    # ### end Alembic commands ###
